restrito/urls.py
from django.urls import path
from restrito import views

app_name = 'restrito'
urlpatterns = [
    path('aluno/', views.aluno, name="aluno"),
    path('professor/', views.professor, name="professor"),
    path('perfil/turma/idturma/', views.turma, name="turma"),
    path('perfil/turma/idturma/atividade/idatividade/', views.atividade, name="atividade"),
]

restrito/models.py
from django.db import models

# Create your models here.

restrito/models/aluno.py
from django.db import models

class Aluno(models.Model):

    nome = models.CharField("Nome Completo", max_length=120)
    email = models.EmailField("Email")
    celular = models.CharField("Celular", max_length=15)
    apelido = models.CharField("Apelido", max_length=120)
    usuario = models.ForeignKey('restrito.Usuario', on_delete=models.CASCADE)

    class Meta:
        db_table = 'ALUNO'

restrito/models/professor.py
from django.db import models

class Professor(models.Model):

    nome = models.CharField("Nome Completo", max_length=120)
    email = models.EmailField("Email")
    celular = models.CharField("Celular", max_length=15)
    apelido = models.CharField("Apelido", max_length=120)
    usuario = models.ForeignKey('restrito.Usuario', on_delete=models.CASCADE)

    class Meta:
        db_table = 'PROFESSOR'

restrito/models/usuario.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager


TIPOS = (
    ('C', 'Coordenador'),
    ('P', 'Professor'),
    ('A', 'Aluno')
)

class UsuarioManager(UserManager):
    
    def _create_user(self, username, password, **extra_fields):
        if not username:
            raise ValueError('Nome de usuário é obrigatório')
        username = self.model.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('tipo', 'C')
        return self._create_user(username, password, **extra_fields) 

class Usuario(AbstractBaseUser):
    username = models.CharField(
        "Nome de Usuário", max_length=120,
        unique=True     
    )

    data_expiracao = models.DateField(
        "Data Expiração",
        null=True
    )

    tipo = models.CharField(
        "Tipo de usuário",
        max_length=1,
        choices=TIPOS
    )

    objects = UsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.tipo == 'C'

    class Meta:
        db_table = 'USUARIO'

restrito/views.py
from django.shortcuts import render

# Create your views here.

def aluno(request):
    context = {
        "titulo":"Área do Aluno",
    }
    return render(request, "aluno.html", context)

def professor(request):
    context = {
        "titulo":"Área do Professor",
    }
    return render(request, "professor.html", context)

def turma(request):
    context = {
        "titulo":"Turma",
    }
    return render(request, "turma.html", context)

def atividade(request):
    context = {
        "titulo":"Atividades",
    }
    return render(request, "atividade.html", context)

restrito/templates/aluno.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Area do Aluno</h1>

    <h2>Turmas matriculadas</h2>
    <a class="nav-link" href="{% url 'restrito:turma' %}">Turmas</a>
    
    <h2>Mensagens recebidas</h2>

    <h2>Atividades pendentes</h2>
    <a class="nav-link" href="{% url 'restrito:atividade' %}">Atividades</a>

{% endblock  %}

restrito/templates/atividade.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Atividades</h1>

{% endblock  %}

restrito/templates/professor.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Area do Professor</h1>

    <h2>Turmas matriculadas</h2>
    <a class="nav-link" href="{% url 'restrito:turma' %}">Turmas</a>
    
    <h2>Mensagens recebidas</h2>

    <h2>Atividades pendentes</h2>
    <a class="nav-link" href="{% url 'restrito:atividade' %}">Atividades</a>

{% endblock  %}

restrito/templates/turma.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Turmas</h1>

{% endblock  %}