curriculo/urls.py
from django.urls import path

from curriculo import views

app_name = "curriculo"
urlpatterns = [
    path('novo/', views.novo_curso, name='novo_curso'),
    path('<str:sigla>/', views.curso, name="curso"),
    path('<str:sigla>/disciplina/<str:abrev>/', views.disciplina, name="disciplina"),
]

curriculo/models.py
from django.db import models

TIPOS = (
    ('TECNICO', 'Técnico'),
    ('GRADUACAO', 'Graduação'),
    ('PGRADUACAO', 'Pós-Graduação')
)

SEMESTRES = (
    ('PRIMEIRO', 'Primeiro Semestre'),
    ('SEGUNDO', 'Segundo Semestre'),
    ('TERCEIRO', 'Terceiro Semestre'),
    ('QUARTO', 'Quarto Semestre')
)

# Create your models here.
class Curso(models.Model):
    nome = models.CharField('Nome', max_length=120)

    sigla = models.CharField("Sigla", max_length=5, unique=True)

    tipo = models.CharField("Tipo", max_length=30, choices = TIPOS)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'CURSO'


class Disciplina(models.Model):

    nome = models.CharField("Nome", max_length=120)

    abrev = models.CharField("Abreviação", max_length=10, default='Abreviação', unique=True)

    curso = models.ForeignKey(Curso, on_delete=models.DO_NOTHING)

    descricao = models.TextField("Descrição", null=True, max_length=500)

    ementa = models.TextField("Ementa", null=True, max_length=500)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'DISCIPLINA'


class DisciplinasOfertadas(models.Model):

    curso = models.ForeignKey(Curso, on_delete=models.DO_NOTHING)

    disciplina = models.ForeignKey(Disciplina, null=True, on_delete=models.DO_NOTHING)

    semestre = models.CharField("Semestre", max_length=120, choices = SEMESTRES)

    ano = models.IntegerField("Ano", null=True)
    
    class Meta:
        db_table = 'DISCIPLINAOFERTADA'
        verbose_name = 'Disciplina Ofertada'
        verbose_name_plural = 'Disciplinas Ofertadas'

curriculo/forms.py
from django import forms
from curriculo.models import Curso

class CursoForm(forms.ModelForm):

    class Meta:
        model = Curso
        fields = ['nome', 'sigla', 'tipo']

curriculo/views.py
from django.shortcuts import render, get_object_or_404
from curriculo.models import Curso, Disciplina
from curriculo.forms import CursoForm

def curso(request, sigla):
    curso = get_object_or_404(Curso, sigla=sigla)
    context = {
        "atual": curso
    }
    return render(request, "curriculo/curso.html", context)

def disciplina(request, sigla, abrev):
    disciplinas = get_object_or_404(Disciplina, abrev=abrev)
    context = {
        "detalhes": disciplinas
    }
    return render(request, "curriculo/disciplina.html", context)

def novo_curso(request):
    context = {}

    if request.POST:
        pass
    else:
        form =  CursoForm()
    context["form"] = form
    
    return render(request, "curriculo/novo_curso.html")

curriculo/templates/curriculo/curso.html
{% extends "base.html" %}

{% block titulo %}
    {{ atual.sigla }}
{% endblock %}

{% block conteudo %}
    <h1>{{ atual.nome }}</h1>
    <p>{{ atual.descricao }}</p>
    <p>Coordenador: {{ atual.coordenador }}</p>
    <h2>Disciplinas:</h2>

    <br>

    <h4>Primeiro Semestre</h4>
    {% for disciplinaOf in disciplinasOfertadas %}
        {% if disciplinaOf.curso == atual and disciplinaOf.semestre == 'PRIMEIRO' %}
        <p><a class="nav-link" href="{% url 'curriculo:disciplina' atual.sigla disciplinaOf.disciplina.abrev %}">{{ disciplinaOf.disciplina }}</a></p>
        {% endif %}
    {% endfor %}

    <br>

    <h4>Segundo Semestre</h4>
    {% for disciplinaOf in disciplinasOfertadas %}
        {% if disciplinaOf.curso == atual and disciplinaOf.semestre == 'SEGUNDO' %}
        <p><a class="nav-link" href="{% url 'curriculo:disciplina' atual.sigla disciplinaOf.disciplina.abrev %}">{{ disciplinaOf.disciplina }}</a></p>
        {% endif %}
    {% endfor %}

    <br>

    <h4>Terceiro Semestre</h4>
    {% for disciplinaOf in disciplinasOfertadas %}
        {% if disciplinaOf.curso == atual and disciplinaOf.semestre == 'TERCEIRO' %}
        <p><a class="nav-link" href="{% url 'curriculo:disciplina' atual.sigla disciplinaOf.disciplina.abrev %}">{{ disciplinaOf.disciplina }}</a></p>
        {% endif %}
    {% endfor %}

    <br>

    <h4>Quarto Semestre</h4>
    {% for disciplinaOf in disciplinasOfertadas %}
        {% if disciplinaOf.curso == atual and disciplinaOf.semestre == 'QUARTO' %}
        <p><a class="nav-link" href="{% url 'curriculo:disciplina' atual.sigla disciplinaOf.disciplina.abrev %}">{{ disciplinaOf.disciplina }}</a></p>
        {% endif %}
    {% endfor %}


{% endblock  %}

curriculo/templates/curriculo/disciplina.html
{% extends "base.html" %}

{% block titulo %}
    {{ detalhes.abrev }}
{% endblock %}

{% block conteudo %}
    <h1>{{ detalhes.nome }}</h1>
    <h3>Descrição:</h3>
    <p>{{ detalhes.descricao }}</p>
    <h3>Ementa:</h3>
    <p>{{ detalhes.ementa }}</p>

{% endblock  %}

curriculo/templates/curriculo/novo_curso.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Novo Curso</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar</button>

    </form>
{% endblock  %}