core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name="home" ),
    path('contact/', views.contato, name="contato"),
    path('entrar/', views.entrar, name="entrar"),
    path('sair/', views.sair, name="sair")
]

core/forms.py
from django import forms

from django.core.mail import EmailMessage

class ContatoForm(forms.Form):

    email = forms.EmailField()
    nome = forms.CharField()
    #assunto = forms.
    mensagem = forms.CharField()

    def is_valid(self):
        valido = super(ContatoForm, self).is_valid()
        if valido:
            self.enviar_email()
        return valido


    def enviar_email(self):
        print("Nome: "+self.cleaned_data["nome"])
        print("E-mail: "+self.cleaned_data["email"])
        print("Mensagem:")
        print(self.cleaned_data["mensagem"])
        #send_mail()

class LoginForm(forms.Form):
    login = forms.CharField()
    senha = forms.CharField()

    def is_valid(self):
        valido = super(LoginForm, self).is_valid()
        if valido:
            self.enviar_email()
        return valido

    def enviar_email(self):
        print("Login: "+self.cleaned_data["login"])
        print("Senha: "+self.cleaned_data["senha"])
        #send_mail()

core/views.py
from django.shortcuts import render, redirect

from .forms import ContatoForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages 

# Create your views here.
def home(request):
    context = {
        "titulo":"Outro Título",
    }
    return render(request, "index.html", context)

def contato(request):
    context = {}

    if request.POST:
        form = ContatoForm(request.POST)
        if form.is_valid():
            context["mensagem"] = "Mensagem enviada com sucesso"
        else:
            context["mensagem"] = "Problemas ao enviar a mensagem"
    else:
        form = ContatoForm()

    context["form"] = form
    return render(request, "contato.html", context)

def entrar(request):
    context = {}

    if request.POST:
        username = request.POST.get('login')
        senha = request.POST.get('senha')

        usuario = authenticate(username=username, password=senha)
    
        if usuario:
            login(request, usuario)
            if usuario.tipo == 'P':
                return redirect('arearestrita:home_professor')
            elif usuario.tipo == 'A':
                return redirect('arearestrita:home_aluno')
            else:
                return redirect('admin:index')
            
        else:
            messages.error(request, 'Usuário ou senha inválidos')

    return render(request, "login.html", context)

def sair(request):
    logout(request)
    return redirect('core:home')

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LMS - {% block titulo %} {% endblock  %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous" defer></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" defer></script>
        
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
            <a class="navbar-brand" href="{% url 'core:home' %}">LMS IMPACTA</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Cursos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for curso in curso  %}
                                <a class="dropdown-item" href="{% url 'curriculo:curso' curso.sigla %}">
                                    {{ curso.nome }}
                                </a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:contato' %}">Contato</a>
                    </li>
                </ul>

                {% if not user.is_authenticated %}
                <a role="button" href="{% url 'core:entrar' %}" class="btn btn-outline-success">Entrar</a>
                {% else %}
                    {% if user.tipo == 'C' %}
                        <p>Bem vindo à área do coordenador, {{ user }}</p>
                        <a role="button" href="{% url 'admin:index' %}" class="btn btn-outline-success">Area do Coordenador</a>
                        <a role="button" href="{% url 'core:sair' %}" class="btn btn-outline-success">Sair</a>
                    {% elif user.tipo == 'P' %}
                        <p>Bem vindo à área do professor, {{ user }}</p>
                        <a role="button" href="{% url 'arearestrita:home_professor' %}" class="btn btn-outline-success">Area do Professor</a>
                        <a role="button" href="{% url 'core:sair' %}" class="btn btn-outline-success">Sair</a>
                    {% else %}
                        <p>Bem vindo à área do aluno, {{ user }}</p>
                        <a role="button" href="{% url 'arearestrita:home_aluno' %}" class="btn btn-outline-success">Area do Aluno</a>
                        <a role="button" href="{% url 'core:sair' %}" class="btn btn-outline-success">Sair</a>
                    {% endif %}
                {% endif %}
    
            </div>
        </nav>

    </header>
    <main>
        {% if mensagem %}
            <div class="alert alert-primary" role="alert">
                {{ mensagem }}
            </div>
        {% endif %}
        {% block conteudo %}
        
        {% endblock %}
    </main>
    <footer>
        <hr/>
        <p class="text-center">Todos os direitos reservados Faculdade Impacta 2018</p>
    </footer>
</body>

</html>

core/templates/contato.html
{% extends "base.html" %}

{% block conteudo %}
<h1>Entre em Contato!</h1>

<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.email.errors }}
        <label for="exampleInputEmail1">Email</label>
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" required>
    </div>
    <div class="form-group">
        {{ form.nome.errors }}
        <label for="exampleInputPassword1">Nome</label>
        <input type="text" name="nome" class="form-control" id="exampleInputPassword1" required>
    </div>
    <div class="form-group">
        {{ form.mensagem.errors }}
        <label for="mensagem">Mensagem</label>
        <textarea id="mensagem" name="mensagem" class="form-control" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock  %}


core/templates/curso.html
{% extends "base.html" %}

{% block conteudo %}
    <h1>Curso Algo</h1>
{% endblock  %}
        

core/templates/index.html
{% extends "base.html" %}

{% block titulo %} Home {% endblock  %}

{% block conteudo %}
    <h1>Faculdade Impacta de Tecnologia</h1>
{% endblock  %}

core/templates/login.html
{% extends "base.html" %}

{% block conteudo %}
<h1>Faça login</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="entrar-usuario">Login</label>
        <input type="text" name="login" class="form-control" id="entrar-usuario" required>
    </div>
    <div class="form-group">
        <label for="entrar-senha">Senha</label>
        <input type="password" name="senha" class="form-control" id="entrar-senha" required>
    </div>

    <button type="submit" class="btn btn-primary">Entrar</button>
</form>

{% endblock  %}
